from .medicoSerializer import MedicoSerializer
from .enfermeroSerializer import EnfermeroSerializer
from .userSerializer import UserSerializer
from .pacienteSerializer import PacienteSerializer
from .diagnosticoSerializer import DiagnosticoSerializer
from .familiarSerializer import FamiliarSerializer