# Generated by Django 4.1.1 on 2022-09-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
