# Generated by Django 4.1.1 on 2022-09-19 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicli', '0006_historia_clinica_signos_vitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicli.paciente'),
        ),
    ]
