# Generated by Django 4.1.1 on 2022-09-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicli', '0007_medico_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Fecha_Toma',
            new_name='fecha_toma',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Frecuencia_Respiraoria',
            new_name='frecuencia_respiraoria',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Glicemia',
            new_name='glicemia',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Oximetria',
            new_name='oximetria',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Presion_Arterial',
            new_name='presion_arterial',
        ),
        migrations.RenameField(
            model_name='signos_vitales',
            old_name='Temperatura',
            new_name='temperatura',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='diagnostico',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='historiaClinica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicli.historia_clinica'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicli.medico'),
        ),
        migrations.AddField(
            model_name='enfermero',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicli.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='familiar',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='medicli.familiar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='historia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicli.historia_clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signos_vitales',
            name='historia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicli.historia_clinica'),
        ),
    ]
