# Generated by Django 4.1.1 on 2022-10-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicli', '0009_rename_frecuencia_cardiaca_signos_vitales_frecuencia_cardiaca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL),
        ),
    ]
