# Generated by Django 4.1.1 on 2022-10-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicli', '0011_alter_familiar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermero',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
