from .userView import UserCreateView
from .userDetailView import UserDetailView
from .PacienteView import PacienteList
from .PacienteView import PacienteDetail
from .MedicoView import MedicoList
from .MedicoView import MedicoDetail
from .EnfermeroView import EnfermeroList
from .EnfermeroView import EnfermeroDetail
from .FamiliarView import FamiliarList
from .FamiliarView import FamiliarDetail
from .DiagnosticoView import DiagnosticoList
from .DiagnosticoView import DiagnosticoDetail
from .Signos_vitalesView import Signos_vitalesList
from .Signos_vitalesView import Signos_vitalesDetail