from .medicoCreateView import MedicoCreateView  
from .medicoDetailView import MedicoDetailView
from .enfermeroCreateView import EnfermeroCreateView  
from .enfermeroDetailView import EnfermeroDetailView
from .diagnosticoCreateView import DiagnosticoCreateView
from .diagnosticoDetailView import DiagnosticoDetailView
from .familiarCreateView import FamiliarCreateView
from .familiarDetailView import FamiliarDetailView
from .userView import UserCreateView
from .userDetailView import UserDetailView
from .pacienteCreateView import PacienteCreateView
from .pacienteDetailView import PacienteDetailView