from http.client import ImproperConnectionState
from .user import User
from .paciente import Paciente
from .medico import Medico
from .enfermero import Enfermero
from .familiar import Familiar
from .diagnostico import Diagnostico
from .historia_clinica import Historia_clinica
from .signos_vitales import Signos_vitales
